name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '7.0.103' 

jobs:
  build-and-test:
    runs-on: windows-latest
    timeout-minutes: 15

#    name: build-and-test-${{matrix.os}}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path:
          ~/.csproj

    - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: dotnet list package
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

#    - name: Install dependencies
#      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --blame --no-restore --verbosity quiet
